### ISSUE TITLE
install bombs at MAKE_RESOURCES.sh

### ISSUE THREAD

**Issue by licarna** [google/tsviewdb#1]
I get this error when I try to MAKE_RESOURCES.

[root@tsviewdb var]# $GOPATH/src/github.com/google/tsviewdb/MAKE_RESOURCES.sh
cp: cannot stat `/root/tsviewdb-0.1.linux-amd64/src/code.google.com/p/plotinum/vg/fonts/*': No such file or directory

I've never used google go before, but it seems like this might be broken.

go get code.google.com/p/plotinum/

**Comment by adilhn** [comment]
Perhaps you don't have Mercurial installed?  http://mercurial.selenic.com/wiki/Download

Which platform are you using?  And what do you see if you type:
  go get code.google.com/p/plotinum/plot

Thanks for reporting!

**Comment by licarna** [comment]
That was it.  Thanks!
